version: '3.8'
services:
  webapp:
    build: ./app
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=mysql+pymysql://webapp:password@db/webappdb
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: webappdb
      MYSQL_USER: webapp
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
